apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for storage.openloft.cn/v1, Kind: VirtualCluster
##
- apiGroups:
  - storage.openloft.cn
  resources:
  - virtualclusters
  - virtualclusters/status
  - virtualclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"

##
## Extra rules used by the controller manager
##
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingressclasses"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["limitranges", "resourcequotas"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]

#+kubebuilder:scaffold:rules
