# permissions for end users to edit virtualclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vcluster-operator
    app.kubernetes.io/part-of: vcluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtualcluster-editor-role
rules:
- apiGroups:
  - storage.openloft.cn
  resources:
  - virtualclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.openloft.cn
  resources:
  - virtualclusters/status
  verbs:
  - get
